### ISSUE TITLE
Questions:

### ISSUE THREAD

**Issue by molinto** [DragonflyPie/time-journey#4]
1) Why does the image not load on the 1st question (on the demo too)?
2) Does it show questions previously answered by that user?
3) Is it straight forward enough to add the Facebook provider? 
4) Could the slider be a different colour on the mouse drag?
5) Could the KM be changed to MILES?

Thanks for your time

**Comment by DragonflyPie** [comment]
Hi! Thank you for your questions. I will do my best to answer but bear in mind - its just a small educational project made some time ago and i am not currently supporting it  ;)
1.Hmm, I do not have this problem the demo. But there are some images failing to load due to hosting issues. 
2.If i remember correctly - it shows only unique questions for each user.
3.Yes. You may check nextauth docs https://next-auth.js.org/providers/facebook
4.I think so. Not sure if it is possible with pure css, but definetly possible with useEffect on Slider component.
5.Sure. You can specify units in Google Maps API. Or just use math formula to transform data

**Comment by molinto** [comment]
Awesome, thanks for your helpful response.
